# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.TextField()),
                ('lineos', models.BooleanField(default=False)),
                ('style', models.CharField(default='friendly', max_length=100)),
            ],
            options={
                'verbose_name': '别名',
                'verbose_name_plural': '别名',
                'db_table': 'Snippt',
                'ordering': ('created',),
            },
        ),
    ]
